run-compare-expect.py: Add typing annotations.
The line:

  actualLines = filter(lambda line: not lineIsDropped(line), actualLines)

was causing the error:

  run-compare-expect.py:255: error: Incompatible types in assignment (expression has type "filter[str]", variable has type "list[str]")  [assignment]

which I wasn't able to figure out (WTF is "filter[str]"?), so I
rewrote it.